sonar.projectKey=f7c3c2907a3eef85346e9b5e74142aba2ec907df
sonar.projectName=QA_BUDDY
sonar.sources=backend,frontend/src
sonar.tests=frontend/src
sonar.test.inclusions=frontend/src/**/*.test.jsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.organization=ennded