sonar.projectKey=ennded_AgileBoard
sonar.projectName=AgileBoard
sonar.sources=backend,frontend/src
sonar.tests=frontend/src/tests
sonar.test.inclusions=frontend/src/tests/**/*.test.js,frontend/src/tests/**/*.test.jsx,frontend/src/tests/**/*.spec.js,frontend/src/tests/**/*.spec.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,frontend/src/tests/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.organization=ennded

