name: Docker Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker-backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t agileboard-backend ./backend

  docker-frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend image
        run: docker build -t agileboard-frontend ./frontend

  docker-compose-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose file
        run: docker compose config
